### ISSUE TITLE
Projects list

### ISSUE THREAD

**Issue by felipefernandes** [adrian3/behance-api-template#1]
Hi, 
First congrats about your project is simple and fantastic! So, I'm developing my own based in yours but I wonder where setup quantity of projects, is it possible to configure it? On my I just get with 10 project on the list.

Thanks,
FF

**Comment by adrian3** [comment]
Thanks, FF. The quantity of projects is coming from projectlist.length which should be the total number of projects available. If you want less than the total I think you can replace projectlist.length with the number of projects you want to show. Hope this helps. Good luck.

Adrian

**Comment by felipefernandes** [comment]
Thanks for reply!

I have about 20 projects on my behance, but the api only delivers the last 10 published projects as I suspected with a parameter called 'page'. Well, I stored all page results in a single array and then I call the callback function as you've already done. It worked! Take a look at http://www.felipefernandes.nu

If you wish I can share you my code, or make a push request. :)

thanks,

FF
